title: The Hackers Conference
author: The Hackers Conference
#email: github@anarres.org
baseurl: "" 
url: "https://www.hackersconference.org" 
# logo: /assets/images/new-logo-48.png

# Build settings
#remote_theme: BDHU/minimalist
remote_theme: aterenin/minima-reboot
plugins:
- jekyll-remote-theme

