title: Hackers Conference
email: github@anarres.org
baseurl: "" 
url: "https://www.hackersconference.org" 
color-scheme: auto

# Sidebar
sidebar:
- name: Home
  link: /
- name: About
  link: /about

# Build settings
remote_theme: BDHU/minimalist
plugins:
- jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
git@github.com:BDHU/minimalist.git